node('master') 
{
    stage('CD-S1-Git-Payment') 
	{
      git 'https://github.com/BABJI-AWS-DEVOPS/BATCH45VENUWARFILE.git'
    }
}
node('master') 
{
    stage('CD-S2-Maven-Payment') 
	{
    sh 'mvn package'
    }
}
